config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'items/vouchers'
  get 'items/face'
  get 'items/body'
  get 'cart/thankyou'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  devise_for :users
  resources :items
  get 'pages/about'
  get 'pages/contact'
  get 'pages/treatments'
  get 'pages/welcome'

  root 'pages#welcome'

end

app/models/item.rb
class Item < ActiveRecord::Base
  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def cart  
    session[:cart] ||= {}
  end

  protected
  


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]
  
  def add
    id = params[:id] 
    cart[id] ? cart[id] = cart[id] + 1 : cart[id] = 1 
    redirect_to :action => :index
  end
    
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end
  
  def index
    #if there is a cart pass it to the page for display else pass an empty value
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def index
    @items = Item.all
    if params[:search]
      @items= Item.search(params[:search]).order("created_at ASC")
    else
      @items = Item.all.order('created_at ASC')
    end
  end
  
  def vouchers
    @items = Item.all
  end
  
  def body
    @items = Item.all
  end
  
  def face
    @items = Item.all
  end
  
private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :category, :stock, :img_url)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:price, :products, :customer)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
  
  def treatments
  end
  
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cart/index.html.erb
<h1>Your cart</h1>
<% if @cart.empty? %>
  <p></p>
<% else %>
  <%= link_to "Empty cart", cart_clear_path, class: "btn btn-danger" %>
<% end %>

<% total = 0 %>
<% $count = 0 %>

<table class="table" border = "0">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
<% if @cart.empty? %>
  <p></p>
<% else %>
  <% @cart.each do |id, qty| %>
    <tr>
      <% item = Item.find_by_id(id) %>
        <td><%= image_tag("#{item.img_url}", height: '50%')%></td>
        <td><%= link_to item.name, item %></td>
        <td><%= item.description %></td>
        <td><p><%= qty %></p></td>
        <td><%= number_to_currency(item.price, unit: '€') %></td>
        <% $count += qty %>
        <% total += qty*item.price %>
      <% end %>
<% end %>
<% $running = number_to_currency(total, unit: '€') %>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <th>Total:</th>
    <td><b></b><%= number_to_currency(total, unit: '€') %></b></td>
  </tr>
</table>

<%= link_to "Checkout", cart_thankyou_url, class: "btn btn-primary" %>

app/views/cart/thankyou.html.erb
<p> Thank you for your order. Click <%= link_to "here", cart_clear_path, class: "btn btn-link" %> to continue.</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descrption %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :img_url, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/items/body.html.erb
<%= render 'layouts/itemheader' %>
<div class="row">
  <% @items.each do |item| %>
    <% if item.category == 'Body'%>
    <div class="col-md-3">
        <%= image_tag item.img_url %>
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= item.description %></p>
          <p><%= number_to_currency(item.price, unit: '€') %></p>
          <a href="/cart/<%= item.id %>" class="btn btn-danger">Add To Cart</a>
          
          <% if current_user.try(:admin?) %>
            <%= link_to 'Show', item, class:"btn btn-link" %>  
            <%= link_to 'Edit', edit_item_path(item), class:"btn btn-link" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
          <% end %>
        </div>
    </div>
    <% end %>
  <% end %>
</div>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item, class:"btn btn-link" %> |
<%= link_to 'Back', items_path, class:"btn btn-link" %>

app/views/items/face.html.erb
<%= render 'layouts/itemheader' %>
<div class="row">
  <% @items.each do |item| %>
    <% if item.category == 'face'%>
    <div class="col-md-3 center">
        <%= image_tag item.img_url %>
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= item.description %></p>
          <p><%= number_to_currency(item.price, unit: '€') %></p>
          <a href="/cart/<%= item.id %>" class="btn btn-danger">Add To Cart</a>
          
          <% if current_user.try(:admin?) %>
            <%= link_to 'Show', item, class:"btn btn-link" %>  
            <%= link_to 'Edit', edit_item_path(item), class:"btn btn-link" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
          <% end %>
        </div>
    </div>
    <% end %>
  <% end %>
</div>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/index.html.erb
<%= render 'layouts/itemheader' %>
<div class="row">
  <% @items.each do |item| %>
    <div class="col-md-3 center">
        <%= image_tag item.img_url %>
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= item.description %></p>
          <p><%= number_to_currency(item.price, unit: '€') %></p>
          <a href="/cart/<%= item.id %>" class="btn btn-danger">Add To Cart</a>
          
          <% if current_user.try(:admin?) %>
            <%= link_to 'Show', item, class:"btn btn-link" %>  
            <%= link_to 'Edit', edit_item_path(item), class:"btn btn-link" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
          <% end %>
        </div>
    </div>
  <% end %>
</div>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path, class:"btn btn-link" %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
        <%= image_tag @item.img_url %>
    </div>
  <div class="col-md-6">
    <h3><%= @item.name %></h3>
    <p><%= @item.description %></p>
    <p><%= number_to_currency(@item.price) %></p>
  </div>
</div>
<%= link_to 'Back', items_path, class:"btn btn-link" %>

app/views/items/vouchers.html.erb
<%= render 'layouts/itemheader' %>
<div class="row">
  <% @items.each do |item| %>
    <% if item.category == 'vouchers'%>
    <div class="col-md-3 center">
        <%= image_tag item.img_url %>
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= item.description %></p>
          <p><%= number_to_currency(item.price, unit: '€') %></p>
          <a href="/cart/<%= item.id %>" class="btn btn-danger">Add To Cart</a>
          
          <% if current_user.try(:admin?) %>
            <%= link_to 'Show', item, class:"btn btn-link" %>  
            <%= link_to 'Edit', edit_item_path(item), class:"btn btn-link" %>
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
          <% end %>
        </div>
    </div>
    <% end %>
  <% end %>
</div>

<br>

<% if current_user.try(:admin?) %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/layouts/_footer.html.erb
<p>Copyright 2016</p>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbarbottom navbar navbar-default" role="navigation">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/items"><%= image_tag("logo.png", height: '50')%></a>
      </div>  
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", pages_about_path %> </li>
          <li><%= link_to "Contact", pages_contact_path %></l>
          <% if user_signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
          <% if $count == 0 %>
            <li><%= link_to "Cart", cart_path %></li>
          <% else %>
          <li><%= link_to "Cart (#{$running})", cart_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</div>  

app/views/layouts/_itemheader.html.erb
<nav class="navbar navbar-default" role="navigation">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/items">All Products</a></li>
        <li><a href="/items/face">Face</a></l>
        <li><a href="/items/body">Body</a></l>
        <li><a href="/items/vouchers">Vouchers</a></l>
        <li><a href="/pages/treatments">Treatments</a></l>
      </ul>
              <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <%= form_tag(items_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
                <%= submit_tag "GO", class: 'btn btn-default' %>
            <% end %>
          </div>
        </form>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mbeautyshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :products %><br>
    <%= f.text_field :products %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.number_field :customer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Products</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.price %></td>
        <td><%= order.products %></td>
        <td><%= order.customer %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Products:</strong>
  <%= @order.products %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
      <div class="container">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <%= image_tag("salonface.png")%>
        </div>
      </div>
      <div id="about">
        <h2 style="text-align: center;">About</h2>
        <p>The salon is situated at Obsessions at 87 Capel Street, Dublin 1. My aim is to offer the highest possible standard of treamtments including dermalogica and Juliette Armand skin care treatments, all designed to awarn your natural beautry and promote a sense of well-being. I hope to ensure that you the client is 100% happy with your tratment and I look forward to welcoming you soon</p>
        <p>Monica</p>
      </div>
      <div class="container">
        <div class="col-md-5"></div>
        <div class="col-md-2">
          </div>
        <div class="col-md-5"></div>
      </div>

app/views/pages/contact.html.erb
 <head>
    <title>Contact - Monica's Beauty Room</title>
    <link rel="stylesheet" type="text/css" href="css/contactstyle.css">
    <meta charset="UTF-8">
  </head>
 
 <h2 id="contact">Contact</h2>
        <div class="flexbox">
            <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJX_WoBioMZ0gRCGKJyBwj15E&key=AIzaSyAnKx48ycbBCHmypGRJ7bRJSNlIsyZn3XE" allowfullscreen></iframe>
            <div id='contactinfo'>
              <h3>Location:</h3>
              <p>Obsession, 87 Capel Street, Dublin 1</p>
              <table>
                  <tr>
                    <th colspan="2">Opening Hours</th>
                  </tr>
                  <tr>
                    <td>Mon-Wed:</td>
                    <td>10am - 6pm</td>
                  </tr>
                  <tr>
                    <td>Thurs-Fri:</td>
                    <td>10am-7pm</td>
                  </tr>
                  <tr>
                    <tr>
                      <td>Saturday:</td>
                      <td>10am-4pm</td>
                    </tr>
                    <tr>
                  <tr>
                    <td>Sunday:</td>
                    <td>Closed</td>
                  </tr>
                </table>
                <tr>
                    <th colspan="2">0877055720</th>
                  </tr>
              
            </div>

    
      

app/views/pages/welcome.html.erb
      <div class="container">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <%= image_tag("salonface.png")%>
        </div>
      </div>
      <br>
      <h1 style="text-align: center">Welcome to Monica's Beauty Room</h1>
      <br>
      <div class="container">
        <div class="col-md-5"></div>
        <div class="col-md-2">
          <%= link_to "Enter Shop", items_path, class:"btn btn-primary" %>
          </div>
        <div class="col-md-5"></div>
      </div>